### PR TITLE
feat: add tree-crasher implementation for python

### PR DESCRIPTION
**Pull request by Rog3rSm1th**
- Adds support for the Python programming language in tree-crasher
- Adds script to generate seed corpus `scripts/corpora/python.sh`

### CODE REVIEW

**Comment by langston-barrett** [comment]
@Rog3rSm1th Thanks for the contribution! Can you also add this to the Github Actions workflows?

**Comment by Rog3rSm1th** [comment]
Done!

**Review by langston-barrett — APPROVED** [review]

**Comment by langston-barrett** [comment]
Ah, it looks like the Python parser doesn't play nicely with static linking. Can you remove it from the executable builds, but keep it in the crates.io uploads? If that doesn't make sense, just let me know and I'm happy to do it.

**Comment by Rog3rSm1th** [comment]
I removed it from the executable builds, it should now pass the CI.

**Review by langston-barrett — APPROVED** [review]
Thanks again! I'll try to cut a new release soon to get pre-built binaries up.

**Pull request merged**
